### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/product-pack#101]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] product_pack - By @FrancoMaxime - #120
- [ ] sale_product_pack - By @FrancoMaxime - #121
- [x] sale_stock_product_pack - By @victoralmau - #182
- [x] stock_product_pack - By @rven - #124
- [x] website_sale_product_pack - By @lef-adhoc - #165

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by JrAdhoc** [comment]
website_sale_product_pack https://github.com/OCA/product-pack/pull/132

**Comment by victoralmau** [comment]
sale_stock_product_pack https://github.com/OCA/product-pack/pull/182
